# Default values for yncrea-hellomicro.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: lucasgreck/yncrea-hellomicro
  version: latest

service:
  type: NodePort
  nodePort: 30080
  debugNodePort: 30085